on:
  telegram_bot:
    event: text
    token: ${{ secrets.TG_BOT_FOR_FLOMO }}
    config:
      every: "* * * * *"
jobs:
  flomo: 
    name: send-to-flomo
    runs-on: ubuntu-latest
    steps:
      - uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.FLOMO_API }}
          method: post
          content-type: application/json
          data: '{ "content": ${{ on.telegram_bot.outputs.text }} }'
        