on:
  rsshub:
    path:
      # - /douban/group/669481
      - /telegram/channel/NewlearnerChannel
      - /telegram/channel/TGgeek
      - /ncm/artist/74613
      - /weibo/user/7319628020
      - /weibo/user/6136032379
      - /weibo/user/7125193035
      - /bilibili/live/room/4580389
      - /bilibili/live/room/545156
      - /telegram/channel/nCoV2019
      - /ncm/playlist/2345862215
      - /ncm/user/playlist/488860927
      - /zhihu/people/activities/fang-fang-75-69-92
      - /bilibili/user/dynamic/474937176
    config:
      # skipFirst: true
      format: |
        if (item.description) {
          item.description = item.description.replace(/<[^>]*>/g, "")
          if (item.description) {
            item.description = item.description.trim()
            if (item.description.length > 120) {
              item.description = `${item.description.substring(0, 120)}...`
            }
          }
        }
        if (item.title) {
          item.title = item.title.replace(/\[来自.+\]/g, "")
        }
        return item
jobs:
  rsshub:
    name: RssHub to Telegram Bot
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TG_BOT_FOR_RSS }}
          message: |
            <b>${{ on.rsshub.outputs.__channel_title }}</b>
            ${{ on.rsshub.outputs.title }}
            <a href="${{on.rsshub.outputs.link}}">${{on.rsshub.outputs.description}}</a>
          format: html
          disable_web_page_preview: true