on:
  weather:
    apiKey: ${{ secrets.OPENWEATHERMAP_API_KEY }}
    params:
      lat: ${{secrets.LAT_FOR_WEATHER}}
      lon: ${{secrets.LON_FOR_WEATHER}}
      units: metric
    every: "0 22 * * *"
    filter:
      "daily.0.weather.0.main":
        $eq: Rain
jobs:
  notify:
    name: Send notifications
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TG_BOT_FOR_NOTICE }}
          message: |
            <b>Today maybe raining,remember umbrella!</b> #weather
            temp: ${{on.weather.outputs.daily[0].temp.day}}°, ${{on.weather.outputs.daily[0].weather[0].description}} 
          format: markdown